config/routes.rb
Rails.application.routes.draw do
    root 'home#view'
  devise_for :users
  

  get 'home/view'

  get 'home/intra'

  get 'home/dash'

  post 'home/intra'

 
  resources :students

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  helper_method :dump_ldap
  HOST = "ldap.42.fr"
  PORT = 636
  BASE = "ou=2013,ou=people,dc=42,dc=fr"
  FN = "first-name"
  LN = "last-name"

  def view
  	if user_signed_in?
  	  redirect_to home_intra_path
  	end
    if Student.all.empty?
      @html = "DB is in creation... please wait!"
    else
      @html = "DB LOADED"
    end
  end

  def intra
  	if params[:login].blank? or params[:mdp].blank? and !user_signed_in?
  		redirect_to root_path
  		return
  	end
  	if user_signed_in?
  	  @infos = get_infos(current_user[:email])
   	  return
  	end
    c = conn_ldap(params[:login], params[:mdp])
    if log_as(params[:login], params[:mdp], c)
      @infos = search(c,  params[:login], params[:mdp])
    else
      redirect_to :back
    end
  end

  def dash
  end

  def dump_ldap
    c = conn_ldap("jburet", "public6542ENEMY")
    filter = Net::LDAP::Filter.eq("uid", "*")
    treebase = "dc=42,dc=fr"
    c.bind_as(:base => BASE,:filter => "(uid=jburet)", :password => "public6542ENEMY")
    ldap =  c.search( :base => treebase, :filter => filter,  :return_result => true)
  l = Array.new
  ldap.each do |e|
    l.push(:uid => e[:uid].first,
      :cn => e[:cn].first,
      :uidNumber => e[:uidnumber].first,
      :picture => "https://cdn.42.fr/userprofil/profilview/#{e[:uid].first}.jpg",
      :gidNumber => e[:gidnumber].first,
      :mail => e[:alias].first,
      :firstName => e[FN].first,
      :lastName => e[LN].first)
    end
    Student.create(l)
  end

  private
  def log_as(user, mdp, c)
    if c.bind_as(:base => BASE, :filter => "(uid=#{user})", :password => mdp)
      return true
    else
      return false
    end
  end

  private
  def search(c, query, mdp)
    filter = Net::LDAP::Filter.eq("uid", query)
    treebase = "dc=42,dc=fr"
    ldap = c.search( :base => treebase, :filter => filter,  :return_result => true)
    l = Hash.new
    ldap.each do |e|
      l["uid"] = e[:uid].first
      l["cn"] = e[:cn].first,
      l["uidNumber"] = e[:uidnumber].first
      l["picture"] = "https://cdn.42.fr/userprofil/profilview/#{e[:uid].first}.jpg"
      l["gidNumber"] = e[:gidnumber].first
      l["mail"] = e[:alias].first
      l["firstName"] = e[FN].first
      l["lastName"] = e[LN].first
    end
    u = User.where(:email => "#{query}@student.42.fr")
    u.each do |a|
      a.destroy
    end
    sign_in(User.create(:password => mdp, :email => "#{query}@student.42.fr"))	
    return l
  end

  private
  def conn_ldap(user, mdp)
  	 return (Net::LDAP.new(
      :host => HOST,
      :port => PORT,
      :base => BASE,
      :encryption => {:method => :simple_tls},
      :username => user,
      :password => mdp))
  end

  private
  def get_infos(mail)
  	 p = Student.where(:mail => mail)
  	  infos = Hash.new
  	  p.each do |v|
	  	  infos["uid"] = v[:uid]
	      infos["cn"] = v[:cn]
	      infos["uidNumber"] = v[:uidnumber]
	      infos["picture"] = "https://cdn.42.fr/userprofil/profilview/#{v[:uid]}.jpg"
	      infos["gidNumber"] = v[:gidnumber]
	      infos["mail"] = v[:alias]
	      infos["firstName"] = v[FN]
	      infos["lastName"] = v[LN]
  	  end
  	  return infos
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:uid, :cn, :uidNumber, :picture, :gidNumber, :mail, :firstName, :lastName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/dash.html.erb
<h1>Home#dash</h1>
<p>Find me in app/views/home/dash.html.erb</p>

app/views/home/intra.html.erb
<img src="<%= @infos['picture']%>">
<ul>
	<li>
		<a href="https://dashboard.42.fr/user/profile/<%= @infos['uid'] %>">Dashboard profile</a>
	</li>
	<li>
		<a href="https://intra.42.fr/user/<%= @infos['uid']%>">Intra profile</a>
	</li>
</ul>
<ul>
<% @infos.each do |a, v|%>
	<li>
		<p><%= a %></p>
		<h6><%= v %></h6>
	</li>
<% end %>
</ul>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/home/view.html.erb
<% if Student.all.empty? %>
  	<%= dump_ldap %>
<% else %>
	<%= form_tag(:controller => "home", :action => "intra") do %>
		login :<%= text_field_tag(:login) %>
		password :<%= password_field_tag(:mdp) %>
		<%= submit_tag("connect yourself") %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= link_to "Profile", home_intra_path %>
<%= link_to "Ldap", students_path %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/student/_form.html.erb
<%= form_for @student, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :uid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cn, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :uidNumber, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uidNumber, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :picture, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gidNumber, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gidNumber, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mail, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mail, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :firstName, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firstName, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lastName, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lastName, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                student_path, :class => 'btn' %>
  </div>
<% end %>

app/views/student/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/student/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:uid) %></th>
      <th><%= model_class.human_attribute_name(:cn) %></th>
      <th><%= model_class.human_attribute_name(:uidNumber) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:gidNumber) %></th>
      <th><%= model_class.human_attribute_name(:mail) %></th>
      <th><%= model_class.human_attribute_name(:firstName) %></th>
      <th><%= model_class.human_attribute_name(:lastName) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.uid %></td>
        <td><%= student.cn %></td>
        <td><%= student.uidNumber %></td>
        <td><%= student.picture %></td>
        <td><%= student.gidNumber %></td>
        <td><%= student.mail %></td>
        <td><%= student.firstName %></td>
        <td><%= student.lastName %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/student/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/student/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @student.uid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cn) %>:</strong></dt>
  <dd><%= @student.cn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uidNumber) %>:</strong></dt>
  <dd><%= @student.uidNumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= @student.picture %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gidNumber) %>:</strong></dt>
  <dd><%= @student.gidNumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mail) %>:</strong></dt>
  <dd><%= @student.mail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firstName) %>:</strong></dt>
  <dd><%= @student.firstName %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastName) %>:</strong></dt>
  <dd><%= @student.lastName %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              student_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :cn %><br>
    <%= f.text_field :cn %>
  </div>
  <div class="field">
    <%= f.label :uidNumber %><br>
    <%= f.number_field :uidNumber %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :gidNumber %><br>
    <%= f.number_field :gidNumber %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Cn</th>
      <th>Uidnumber</th>
      <th>Picture</th>
      <th>Gidnumber</th>
      <th>Mail</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.uid %></td>
        <td><%= student.cn %></td>
        <td><%= student.uidNumber %></td>
        <td><%= student.picture %></td>
        <td><%= student.gidNumber %></td>
        <td><%= student.mail %></td>
        <td><%= student.firstName %></td>
        <td><%= student.lastName %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @student.uid %>
</p>

<p>
  <strong>Cn:</strong>
  <%= @student.cn %>
</p>

<p>
  <strong>Uidnumber:</strong>
  <%= @student.uidNumber %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @student.picture %>
</p>

<p>
  <strong>Gidnumber:</strong>
  <%= @student.gidNumber %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @student.mail %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @student.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastName %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>